apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-backend-image:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: upload-storage
              mountPath: /app/uploads
            - name: public-storage
              mountPath: /app/public
      volumes:
        - name: upload-storage
          emptyDir: {}
        - name: public-storage
          emptyDir: {}