apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: droplink-fe-dpl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: your-frontend-image
        env:
        - name: REACT_APP_BACKEND_URL
          value: "http://backend:8080"
        ports:
        - containerPort: 3000
