apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: droplink-be-svc
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
