apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: droplink-fe-svc
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
